#-------------------------------------------------------------
# Terminal colours
#-------------------------------------------------------------

export CLICOLOR=1
export LSCOLORS=ExFxCxDxBxegedabagacad


#-------------------------------------------------------------
# Bash history
#-------------------------------------------------------------

# Enable bash history.
set -o history
# History length.
HISTSIZE=1000
# Bash history file length.
HISTFILESIZE=10000
# Don't put duplicate lines in the history. See bash(1) for more
# options or force ignoredups and ignorespace.
HISTCONTROL=ignoredups:ignorespaec
# Append the history to the histfile instead of overwriting it.
shopt -s histappend
# Update & re-read histfile after every cmd so terminals will share.
export PROMPT_COMMAND="history -n; history -a"


#-------------------------------------------------------------
# Generic Aliases
#-------------------------------------------------------------

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

alias mkdir='mkdir -p'
alias h='history'

alias du='du -kh'
alias df='df -kTh'


#-------------------------------------------------------------
# ls aliases
#-------------------------------------------------------------
alias ll="ls -l"
alias ls='ls -hF'          # add colors for filetype recognition
alias la='ls -lah'         # show hidden files
#alias lx='ls -lXBh'       # sort by extension
#alias lk='ls -lSh'        # sort by size, biggest last
#alias lt='ls -lth'        # sort by date, most recent first
#alias ltr='ls -ltrh'      # sort by date, most recent last


#-------------------------------------------------------------
# spelling typos
#-------------------------------------------------------------

alias xs='cd'
alias vf='cd'
alias moer='more'
alias moew='more'
alias kk='ll'
alias cd..='cd ..'


#-------------------------------------------------------------
# Personnal Aliases
#-------------------------------------------------------------

alias safari='open -a "Safari"'
alias chrome='open -a "Google Chrome"'
alias finder='open -a "Finder"'
alias firefox='open -a "Firefox"'


#-------------------------------------------------------------
# Get readable list of network IPs
#-------------------------------------------------------------
alias ips="ifconfig -a | perl -nle'/(\d+\.\d+\.\d+\.\d+)/ && print $1'"
alias myip="dig +short myip.opendns.com @resolver1.opendns.com"

